title: Onno van Paridon
description: Coding
author: Onno van Paridon
permalink: pretty
theme: minima
github_username:  onnovanparidon
twitter_username: onnovanparidon
instagram_username: onnovanparidon
linkedin_username: onnovanparidon